version: "3.8"
networks:
  testnet:
services:
  server:
    image: node:18
    container_name: "server"
    ports:
      - "1338:1338"
    volumes:
      - ".:/server"
    working_dir: /server
    command: bash -c "npm install && npm run start"
    networks:
      - testnet
    restart: "always"