name: Asqatasun
# Does not work yet!!!

on:
  workflow_dispatch:

jobs:
  asqatasun:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install curl and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y curl jq
      - name: Start Asqatasun docker container
        run: docker-compose -f asqatasun-docker/api-5.0.0-rc.2_ubuntu-18.04/docker-compose.yml up -d
      # - name: Wait for Docker container to start
      #   run: |
      #     sleep 20
      - name: Run Asqatasun
        run: |
          curl http://admin%40asqatasun.org:myAsqaPassword@localhost:8085/api/v0/audit